server:
  port: 8085
  servlet:
    context-path: /auth-service

logging:
  level:
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oauth2
#      authentication-database: admin
#      username: rootUser
#      password: rootPassword