server:
  port: 8086
  servlet:
    context-path: /resource-service

logging:
 level:
  org.springframework.security: DEBUG

rest:
  url:
    auth_server: http://localhost:8085/auth-service/oauth/check_token